#!/usr/bin/env python3
"""Merge acceptance-criteria.md into an existing story-graph.json.

Usage:
    python md_acceptance_criteria_to_story_graph.py <input-ac.md> <story-graph.json>

Format expected (generated by abd-acceptance-criteria skill):

    # Acceptance Criteria -- Increment N: <increment name>
    ...
    ## Story: <story name>

    **Story type:** <actor>

    ### Domain terms
    - *Term* -- definition

    ### Acceptance criteria

    1. **WHEN** the customer ...
       **THEN** the system ...
       **AND** each entry shows ...
       **Evidence:** source -- line N

    2. **WHEN** ...

    ---

Behaviour:
    - Finds every "## Story: <name>" block in the markdown.
    - Collects numbered acceptance criteria items as raw multi-line strings
      (preserving the existing graph string format).
    - Walks the graph and injects AC into the matching story by name.
    - Reports matched and unmatched story names.
    - If the graph file does not exist, exits with an error -- use
      md_story_map_to_story_graph.py first to create the skeleton.
    - If the markdown format is not recognised (no Story blocks found),
      exits with exit code 2 so the caller can fall back to AI generation.
      Name the fallback script with a _<variant> suffix before the stem, e.g.
      md_acceptance_criteria_to_story_graph_<variant>.py.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Format signature — bail early when markdown does not match expected format
# ---------------------------------------------------------------------------

_STORY_HEADER = re.compile(r"^##\s+Story:\s+(.+)", re.MULTILINE)
_AC_ITEM = re.compile(r"^\d+\.\s+\*\*WHEN\*\*", re.MULTILINE)


class UnrecognisedFormatError(ValueError):
    """Raised when the markdown does not contain the expected AC format."""


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

def _extract_ac_block(block: str) -> list[str]:
    """Return a list of raw AC strings from a story block."""
    ac_section = re.split(r"^###\s+Acceptance criteria", block, flags=re.MULTILINE)
    if len(ac_section) < 2:
        return []
    raw = ac_section[1]
    # Stop at the next H3 or H2 heading or horizontal rule
    raw = re.split(r"^(?:---|##|###)", raw, flags=re.MULTILINE)[0]
    return _split_numbered_items(raw.strip())


def _split_numbered_items(text: str) -> list[str]:
    """Split numbered list into individual items, stripping trailing whitespace."""
    boundaries = [m.start() for m in re.finditer(r"^\d+\.", text, re.MULTILINE)]
    if not boundaries:
        return []
    items: list[str] = []
    for i, start in enumerate(boundaries):
        end = boundaries[i + 1] if i + 1 < len(boundaries) else len(text)
        raw = text[start:end].rstrip()
        items.append(raw)
    return items


def parse_acceptance_criteria(md_path: Path) -> dict[str, list[str]]:
    """Return {story_name: [ac_string, ...]} from an acceptance-criteria markdown file."""
    text = md_path.read_text(encoding="utf-8")
    story_blocks = _STORY_HEADER.split(text)
    # story_blocks: [preamble, name1, block1, name2, block2, ...]
    if len(story_blocks) < 3:
        raise UnrecognisedFormatError(
            f"No '## Story:' blocks found in {md_path}. "
            "File may not match the abd-acceptance-criteria format."
        )
    result: dict[str, list[str]] = {}
    i = 1
    while i < len(story_blocks) - 1:
        story_name = story_blocks[i].strip()
        block = story_blocks[i + 1]
        i += 2
        ac_items = _extract_ac_block(block)
        if ac_items:
            result[story_name] = ac_items
    return result


# ---------------------------------------------------------------------------
# Graph injection
# ---------------------------------------------------------------------------

def _all_stories(graph: dict) -> list[dict]:
    """Yield every story dict in the graph."""
    stories: list[dict] = []
    for epic in graph.get("epics", []):
        stories.extend(_stories_from_node(epic))
    return stories


def _stories_from_node(node: dict) -> list[dict]:
    stories: list[dict] = []
    for sg in node.get("story_groups", []):
        stories.extend(sg.get("stories", []))
    for sub in node.get("sub_epics", []):
        stories.extend(_stories_from_node(sub))
    return stories


def inject_acceptance_criteria(
    graph: dict, ac_by_story: dict[str, list[str]]
) -> tuple[int, list[str]]:
    """Inject AC into matching stories. Returns (updated_count, unmatched_names)."""
    matched: set[str] = set()
    updated = 0
    for story in _all_stories(graph):
        name = story.get("name", "")
        if name in ac_by_story:
            story["acceptance_criteria"] = ac_by_story[name]
            matched.add(name)
            updated += 1
    unmatched = [n for n in ac_by_story if n not in matched]
    return updated, unmatched


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main(argv: list[str] = sys.argv[1:]) -> int:
    if len(argv) != 2:
        print(
            "Usage: md_acceptance_criteria_to_story_graph.py <input-ac.md> <story-graph.json>",
            file=sys.stderr,
        )
        return 1

    md_path = Path(argv[0])
    graph_path = Path(argv[1])

    if not md_path.exists():
        print(f"[ERROR] Markdown file not found: {md_path}", file=sys.stderr)
        return 1
    if not graph_path.exists():
        print(
            f"[ERROR] Graph file not found: {graph_path}\n"
            "Create the skeleton first with md_story_map_to_story_graph.py.",
            file=sys.stderr,
        )
        return 1

    try:
        ac_by_story = parse_acceptance_criteria(md_path)
    except UnrecognisedFormatError as exc:
        print(f"[FORMAT] {exc}", file=sys.stderr)
        return 2

    print(f"[PARSE] Found AC for {len(ac_by_story)} stories in {md_path.name}")

    graph = json.loads(graph_path.read_text(encoding="utf-8"))
    updated, unmatched = inject_acceptance_criteria(graph, ac_by_story)

    graph_path.write_text(
        json.dumps(graph, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"[WRITE] Updated {updated} stories in {graph_path}")

    if unmatched:
        print(
            f"\n[WARN] {len(unmatched)} story name(s) in markdown not found in graph:",
            file=sys.stderr,
        )
        for name in unmatched:
            print(f"  - {name}", file=sys.stderr)
        return 1

    print("[OK] All story names matched.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
