#!/usr/bin/env python3
"""Merge thin-slicing.md increments into an existing story-graph.json.

Usage:
    python md_thin_slice_to_story_graph.py <input-thin-slicing.md> <story-graph.json>

Format expected (generated by abd-thin-slicing skill):

    ## Increments

    ### Increment 1: `Name of the increment`

    **Outcome:** ...

    **Slicing notes:** ...

    **Stories in this increment** *(order reflects flow within the slice):*

    - *Story Name* -- optional note
    - *Another Story Name*
    - *Plain Story Name* (role qualifier)

    ---

    ### Increment 2: `...`

Behaviour:
    - Finds every "### Increment N: <name>" block.
    - Extracts story names from the "Stories in this increment" bullet list.
      Story names are wrapped in *italics*, plain bullets, or both.
    - Replaces the "increments" array in the graph with parsed data.
      Each increment entry has: name, priority, stories[{name, sequential_order}].
    - If the graph file does not exist, a minimal scaffold is created
      (empty epics) and increments are written into it.
    - If the markdown format is not recognised (no Increment blocks found),
      exits with exit code 2 so the caller can fall back to AI generation.
      Name the fallback script with a _<variant> suffix before the stem, e.g.
      md_thin_slice_to_story_graph_<variant>.py.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Format signature
# ---------------------------------------------------------------------------

_INCREMENT_HEADER = re.compile(
    r"^###\s+Increment\s+(\d+):\s+[`'\"]?(.+?)[`'\"]?\s*$", re.MULTILINE
)
_STORIES_SECTION = re.compile(
    r"\*\*Stories in this increment\**.*?\n((?:\s*-[^\n]+\n?)+)",
    re.DOTALL,
)
_BULLET_STORY = re.compile(r"^\s*-\s+\*?([^*()\n]+?)\*?\s*(?:\(.*?\))?\s*(?:--(?!>).*)?$")
# Pattern to strip "Actor --> " prefix if the story was incorrectly written with story-map notation.
# e.g. "- System --> Load Crowd from Repository" -> "Load Crowd from Repository"
# Correct format is bare names; this prevents "System" or "GM" being stored as the name.
_ACTOR_PREFIX = re.compile(r"^\w+\s*-->\s*")


class UnrecognisedFormatError(ValueError):
    """Raised when the markdown does not match the expected thin-slicing format."""


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

def _extract_story_names(block: str) -> list[str]:
    """Extract ordered story names from the Stories section of an increment block."""
    match = _STORIES_SECTION.search(block)
    if not match:
        return []
    bullet_block = match.group(1)
    names: list[str] = []
    for line in bullet_block.splitlines():
        m = _BULLET_STORY.match(line)
        if m:
            name = m.group(1).strip().strip("*").strip()
            # Defensively strip "Actor --> " prefix if story-map notation was used by mistake.
            # Correct format is bare names; this prevents "System" or "GM" being stored as the name.
            name = _ACTOR_PREFIX.sub("", name).strip()
            if name:
                names.append(name)
    return names


def parse_increments(md_path: Path) -> list[dict]:
    """Return a list of increment dicts from a thin-slicing markdown file."""
    text = md_path.read_text(encoding="utf-8")
    splits = _INCREMENT_HEADER.split(text)
    # splits: [preamble, num1, name1, block1, num2, name2, block2, ...]
    if len(splits) < 4:
        raise UnrecognisedFormatError(
            f"No '### Increment N:' blocks found in {md_path}. "
            "File may not match the abd-thin-slicing format."
        )

    increments: list[dict] = []
    i = 1
    while i < len(splits) - 2:
        priority = int(splits[i])
        name = splits[i + 1].strip().strip("`'\"")
        block = splits[i + 2]
        i += 3
        story_names = _extract_story_names(block)
        stories = [
            {"name": n, "sequential_order": float(idx + 1)}
            for idx, n in enumerate(story_names)
        ]
        increments.append({"name": name, "priority": priority, "stories": stories})

    return increments


# ---------------------------------------------------------------------------
# Graph injection
# ---------------------------------------------------------------------------

def inject_increments(graph: dict, increments: list[dict]) -> None:
    """Replace the increments array in the graph with the parsed list."""
    graph["increments"] = increments


def _load_or_create_graph(graph_path: Path) -> dict:
    if graph_path.exists():
        return json.loads(graph_path.read_text(encoding="utf-8"))
    return {"epics": []}


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main(argv: list[str] = sys.argv[1:]) -> int:
    if len(argv) != 2:
        print(
            "Usage: md_thin_slice_to_story_graph.py <input-thin-slicing.md> <story-graph.json>",
            file=sys.stderr,
        )
        return 1

    md_path = Path(argv[0])
    graph_path = Path(argv[1])

    if not md_path.exists():
        print(f"[ERROR] Markdown file not found: {md_path}", file=sys.stderr)
        return 1

    try:
        increments = parse_increments(md_path)
    except UnrecognisedFormatError as exc:
        print(f"[FORMAT] {exc}", file=sys.stderr)
        return 2

    print(f"[PARSE] Found {len(increments)} increments in {md_path.name}")
    for inc in increments:
        print(f"  Increment {inc['priority']}: {inc['name']} ({len(inc['stories'])} stories)")

    graph = _load_or_create_graph(graph_path)
    inject_increments(graph, increments)

    graph_path.parent.mkdir(parents=True, exist_ok=True)
    graph_path.write_text(
        json.dumps(graph, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    total_stories = sum(len(inc["stories"]) for inc in increments)
    print(f"[WRITE] {len(increments)} increments, {total_stories} story references written to {graph_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
