"""
MapsContentAssembler — AGENTS.md + agents-staged + per-phase bundles (Instructions-based).

Writes:
  - Repo ``AGENTS.md`` and ``content/built/agents-staged.md`` (flat process + phases, solution preamble stripped)
  - ``content/built/phases/<slug>.md`` (``generate_prompt`` reads these when ``skill-config`` assembly mode is static and the file exists)
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from build_support import (
    demote_first_h1_to_h2,
    phase_fnames_from_skill_config,
    rewrite_links_for_agents_md,
    rewrite_links_for_phase_bundle,
    strip_operator_block_for_agents,
    warn_orphan_rule_files,
    warn_unknown_phase_rule_keys,
)
from instructions import _parts_dir
from maps_instructions import MapsInstructions


class _BuildTimeEngine:
    """Minimal engine surface for MapsInstructions when writing derived files (no workspace context)."""

    workspace_path = None
    context_paths: list = []


def load_skill_config(skill_root: Path) -> dict[str, Any]:
    p = skill_root / "skill-config.json"
    if not p.is_file():
        return {}
    return json.loads(p.read_text(encoding="utf-8"))


class MapsContentAssembler:
    def __init__(self, skill_root: Path, skill_config: dict[str, Any]):
        self.root = Path(skill_root).resolve()
        self.config = skill_config
        self.parts = _parts_dir(self.root)
        self.skill_name = skill_config.get("name", "abd-maps-models-specs")
        self._phase_fnames = phase_fnames_from_skill_config(skill_config)

    def _instructions(self) -> MapsInstructions:
        op = self.config.get("operation_sections", {})
        return MapsInstructions(op, self.root, _BuildTimeEngine(), self.config)

    def merge_agents_flat_body(self) -> str:
        """Process + phases in order; solution preamble stripped; links rewritten for skill root."""
        process_path = self.parts / "process.md"
        if not process_path.is_file():
            raise FileNotFoundError(f"Missing {process_path}")

        proc = process_path.read_text(encoding="utf-8")
        proc = demote_first_h1_to_h2(proc)
        proc = rewrite_links_for_agents_md(proc, self._phase_fnames)

        chunks: list[str] = [proc.rstrip(), "\n"]
        phases_dir = self.parts / "phases"

        for fname in self._phase_fnames:
            p = phases_dir / fname
            if not p.is_file():
                raise FileNotFoundError(f"Missing phase file: {p}")
            body = p.read_text(encoding="utf-8")
            body = strip_operator_block_for_agents(body)
            body = body.strip() + "\n"
            body = demote_first_h1_to_h2(body)
            body = rewrite_links_for_agents_md(body, self._phase_fnames)
            chunks.append("\n\n---\n\n")
            chunks.append(body)

        return "".join(chunks)

    def write_agents_and_staged(self) -> None:
        built = self.root / "content" / "built"
        built.mkdir(parents=True, exist_ok=True)
        body = self.merge_agents_flat_body()

        staged_path = built / "agents-staged.md"
        staged_path.write_text(
            "<!-- Generated by scripts/build.py — do not edit by hand. -->\n\n"
            "# Staged agent bundle\n\n"
            "Intermediate merge (process + phases, solution preamble stripped). "
            "Same markdown body as `AGENTS.md` below the title line.\n\n"
            "---\n\n"
            + body,
            encoding="utf-8",
        )
        print(f"Wrote {staged_path.relative_to(self.root)}", flush=True)

        agents_path = self.root / "AGENTS.md"
        agents_path.write_text(f"# AGENTS — {self.skill_name}\n\n" + body, encoding="utf-8")
        print(f"Wrote {agents_path.relative_to(self.root)}", flush=True)

    def write_built_phase_bundles(self) -> None:
        inst = self._instructions()
        cq_lib = self.config.get("critical_quality_library", "critical-quality-steps.md")

        built = self.root / "content" / "built"
        built.mkdir(parents=True, exist_ok=True)
        phase_bundles_dir = built / "phases"
        phase_bundles_dir.mkdir(parents=True, exist_ok=True)

        for slug in self.config.get("phase_files", []):
            text = inst.assemble_prompt(slug, include_context=False)
            text = rewrite_links_for_phase_bundle(text, self._phase_fnames)
            # One-line marker only so static file matches dynamic assembly (+ link rewrite) aside from this comment.
            full = "<!-- Generated by scripts/build.py — do not edit by hand. -->\n\n" + text

            out = phase_bundles_dir / f"{slug}.md"
            out.write_text(full, encoding="utf-8")
            print(f"Wrote {out.relative_to(self.root)}", flush=True)

        warn_unknown_phase_rule_keys(self.config)
        warn_orphan_rule_files(self.root / "rules", self.config)

        self._write_built_readmes(cq_lib)

    def _write_built_readmes(self, cq_lib: str) -> None:
        built = self.root / "content" / "built"
        built.mkdir(parents=True, exist_ok=True)

        phases_readme = built / "phases" / "README.md"
        phases_readme.parent.mkdir(parents=True, exist_ok=True)
        phases_readme.write_text(
            "# Built phase bundles (`content/built/phases/`)\n\n"
            "Each file is generated by **`scripts/build.py`** via **`MapsInstructions`** (same content as "
            "**`python scripts/generate_prompt.py --phase <slug>`** when **`skill-config.json`** → **`generate_prompt.assembly_mode`** is **`static`** and this file exists).\n\n"
            "**Authoritative phase sources** (edit these, not this folder): `content/parts/phases/<slug>.md`.\n\n"
            "Each bundle contains (in order):\n\n"
            "1. **Role** — `content/parts/solution-analyst-role.md` (headings demoted).\n"
            "2. **Phase** — source `content/parts/phases/<slug>.md` only (no embedded role).\n"
            "3. **Library** — excerpts from **`library_files`** plus **`phase_library[slug]`** in **`skill-config.json`**.\n"
            "4. **Rules** — `rules/*.md` inlined in order per **`phase_rules`** and **`every_phase_rules`** "
            "in **`skill-config.json`** (each entry is the rule file stem without `.md`, same as **abd-skill-builder** "
            "`phase_rules`).\n"
            f"5. **Principles** — **`{cq_lib}`** plus optional **`phase_critical_quality_notes`** (**Stage 2+** only). "
            "**Stage 1** phases (set-workspace … canonical-context) **omit** this section; `principles.md` already appears under **Library** where configured.\n",
            encoding="utf-8",
        )
        print(f"Wrote {phases_readme.relative_to(self.root)}", flush=True)

        root_readme = built / "README.md"
        root_readme.write_text(
            "# `content/built/` — generated merge outputs\n\n"
            "All **built** artifacts for this skill live under this directory (do not edit by hand; run "
            "**`python scripts/build.py`** or **`python scripts/build.py --merge-only`**).\n\n"
            "| Path | Role |\n"
            "| --- | --- |\n"
            "| **`agents-staged.md`** | Intermediate merge: `process.md` + source phase bodies (same body as root **`AGENTS.md`** below its title) |\n"
            "| **`phases/<slug>.md`** | Per-phase static prompt bundle (role → phase → library → rules → principles for Stage 2+; Stage 1 ends after rules) |\n"
            "| **`phases/README.md`** | Describes phase bundle layout |\n",
            encoding="utf-8",
        )
        print(f"Wrote {root_readme.relative_to(self.root)}", flush=True)
